apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - name: spring-app
      port: 8081
      protocol: TCP
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - image: punitg237/springboot-mysql:springboot-app
        name: app-pod
        ports:
        - containerPort: 8081
