apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: NodePort
  selector:
    app: mysqldb
  ports:
    - name: mysqldb
      port: 3306
      protocol: TCP
      targetPort: 3306   

---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - image: mysql
        name: mysqldb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 3306
